#lang scheme
(define (double a) (* a 2))
(define (halve a) (/ a 2))
(define (_times a b x y)
  (cond ((= b 1) (+ x y))
        ((= b 0) 0)
        ((even? b) (_times (double a) (halve b) (double x) y))
        (else (_times a (- b 1) x (+ y a)))
        )
  )
(define (times a b) (_times a b a 0))
(define (check a b) (= (times a b) (* a b)))
(check 2 4)
(check 4 19)
(check 5 2)
(check 5 1)
(check 1 6)
(check 1431 431)
(check 5 0)
(check 0 5)
(check 154 1432)