#lang scheme
(define (variable? x) (and (symbol? x) (not (op? x))))
(define (same-variable? x y) (and (variable? x) (variable? y) (eq? x y)))
(define (sum? x) (and (formula? x) (eq? (cadr x) '+)))
(define (addend x) (car x))
(define (augend x) (if (formula? (cddr x)) (cddr x) (caddr x)))
(define (make-sum a b) (cond ((and (number? a) (number? b)) (+ a b))
                             ((eq? a 0) b)
                             ((eq? b 0) a)
                             (else (list a '+ b))))
(define (product? x) (and (formula? x)(eq? (cadr x) '*)))
(define (multiplier x) (car x))
(define (multiplicand x) (cond ((sum? (cddr x)) (caddr x))
                               ((formula? (cddr x)) (cddr x))
                               (else (caddr x))))
(define (make-product a b) (cond ((and (number? a) (number? b)) (* a b))
                                 ((or (eq? a 0) (eq? b 0)) 0)
                                 ((eq? a 1) b)
                                 ((eq? b 1) a)
                                 (else (list a '* b))
                                 ))
(define (op? x) (or (eq? x '+) (eq? x '*) (eq? x '**)))
(define (formula? x) (and (list? x) (>= (length x) 3) (op? (cadr x))))
(define (exponentiation? x) (and (formula? x) (eq? (cadr x) '**)))
(define (base x) (car x))
(define (exponent x) (caddr x))
(define (make-exponentiation b e) (cond ((and (eq? b 0) (eq? e 0)) (error "0**0" b e))
                                        ((and (number? b) (number? e)) (expt b e))
                                        ((eq? b 0) 0)
                                        ((eq? b 1) 1)
                                        ((eq? e 1) b)
                                        ((eq? e 0) 1)
                                        (else (list b '** e))))
(define (deriv e v)
  (cond ((sum? e) (make-sum (deriv (addend e) v) (deriv (augend e) v)))
        ((product? e) (make-sum (make-product (multiplier e) (deriv (multiplicand e) v)) (make-product (deriv (multiplier e) v) (multiplicand e))))
        ((exponentiation? e) (make-product (exponent e) (make-exponentiation (base e) (make-sum (exponent e) -1))))
        ((variable? e) (if (same-variable? e v) 1 0))
        ((number? e) 0)
        (else (error "unknown expression " e))))
(deriv '(1 + x + 3 * (x + y + 2)) 'x)